### ISSUE TITLE
Android: Unable to instantiate activity ComponentInfo

### ISSUE THREAD

**Issue by i0257** [ReactNativeBrasil/react-native-sum-up#5]
I've been trying to use this plugin in my react-native app with no luck. The current error I get on android looks like this:

```
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.mal.sumuptest/com.sumup.merchant.ui.Activities.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.sumup.merchant.managers.PreferencesManager com.sumup.merchant.CoreState.getUserPreferences()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.sumup.merchant.managers.PreferencesManager com.sumup.merchant.CoreState.getUserPreferences()' on a null object reference
        at com.sumup.merchant.ui.Activities.LoginActivity.<init>(SourceFile:128)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
```
The app crashes with the provided error when I call the methods 'RNSumUp.authenticate()' and 'RNSumUp.authenticateWithToken()'.
So far I've tried using both react-native versions 0.55.4 and 0.57.1.

My code looks like this:
```javascript
RNSumUp.setup("X");

RNSumUp.isLoggedIn().then(function(data) {
	if(!data.isLoggedIn){
		//crashes on the next line
		RNSumUp.authenticateWithToken("My token").then(function(data) {
			console.log(data);
		}).catch(function(reason) {
			console.log(reason);
		});
	} else {
		console.log("Logged in!");
	}
});
```

Any ideas or pointers would be greatly appreciated.

**Comment by ital0** [comment]
Could you provide your MainApplication.java **onCreate** method?

**Comment by i0257** [comment]
onCreate method from my MainApplication.java

```javascript
public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
}
```

**Comment by ital0** [comment]
@i0257 please, import the package **com.sumup.merchant.api.SumUpState** and run this method right after SoLoader: **SumUpState.init(this);**

**Comment by i0257** [comment]
That seemed to be the missing link. Everything is working as intended now, thank you for the help.
